language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6

install:
  pip install -r requirements.txt
  pip install codecov

script:
  - python -m unittest rest_framework/tests/__init__.py
  - coverage run rest_framework/tests/__init__.py

after_success:
  - codecov
