language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

script:
  - pip install coverage codecov
  - python setup.py test  # run tests
  - coverage run setup.py test  # run coverage tests

after_success:
  - codecov  # report to coverage.
  # build docs. FIXME: NOT WORKING
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      pip install -r requirements/requirements-setup.txt;
      mkdocs gh-deploy --remote-branch https://${GH_TOKEN}@github.com/nxexox/python-rest-framework.git;
    fi
