
language: python
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6

install:
  pip install -r requirements/requirements-app.txt -r requirements/requirements-tests.txt

script:
  - python -m unittest rest_framework/tests/__init__.py  # run tests
  - coverage run -m unittest rest_framework/tests/__init__.py  # run coverage tests

after_success:
  - codecov  # report to coverage.
  # build docs.
  - echo "$TRAVIS_BRANCH"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      pip install -r requirements/requirements-setup.txt;
      echo "Hello World!";s
      mkdocs gh-deploy;
    fi
