site_url: https://nxexox.github.io/python-rest-framework/
site_description: Python Rest Framework - Web APIs for Python
site_author: Deys Timofey
site_name: Python Rest Framework

copyright: 'Copyright (c) 2018, Deys Timofey All rights reserved.'

repo_name: GitHub
repo_url: https://github.com/nxexox/python-rest-framework
edit_uri: /blob/master/docs/

nav:
  - Home: 'index.md'
  - API:
    - Serializer fields: 'api-guid/fields.md'
    - Serializers: 'api-guid/serializers.md'
    - Validation: 'api-guid/validators.md'
  - Release Notes: 'release-notes.md'

theme:
  name: null
  custom_dir: 'docs_theme/'

markdown_extensions:
 - toc:
    anchorlink: True
 - smarty
